# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('type_activity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
