# Generated by Django 3.2.7 on 2021-09-27 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('type_activity', models.CharField(blank=True, max_length=250, null=True, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now, verbose_name='Día de tarea')),
                ('daytime', models.TimeField(default=datetime.datetime.now, verbose_name='Hora de la tarea')),
                ('time_spent', models.TimeField(default=0, verbose_name='Tiempo empleado')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_activity', to='activities.activity', verbose_name='Actividad')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='currency.person', verbose_name='Persona que realiza la actividad')),
            ],
            options={
                'verbose_name': 'Actividad realizada',
                'verbose_name_plural': 'Actividades realizadas',
                'ordering': ['day'],
            },
        ),
    ]
