# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0022_entity_percent_validators'),
        ('activities', '0002_personactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='personactivity',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='currency.Person', verbose_name='Persona que realiza la actividad'),
        ),
    ]
