# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20180420_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personactivity',
            options={'ordering': ['day'], 'verbose_name': 'Actividad realizada', 'verbose_name_plural': 'Actividades realizadas'},
        ),
    ]
