# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180422_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='personactivity',
            name='daytime',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora de la tarea'),
        ),
    ]
