# Generated by Django 3.2.7 on 2021-09-27 22:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import helpers.filesystem
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color de etiqueta (código hexadecimal)')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIF')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Descripción corta')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('entities/'), verbose_name='Imagen de perfil')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(default=0, verbose_name='Latitud')),
                ('longitude', models.FloatField(default=0, verbose_name='Longitud')),
                ('bonus_percent_entity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificación a entidades')),
                ('bonus_percent_general', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de bonificación general')),
                ('max_percent_payment', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Máximo porcentaje de pago aceptado')),
                ('num_workers', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de trabajadores')),
                ('legal_form', models.TextField(blank=True, null=True, verbose_name='Formulario legal')),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Página de Facebook')),
                ('webpage_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Página web')),
                ('twitter_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Twitter')),
                ('telegram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Canal de Telegram')),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Perfil de Instagram')),
                ('categories', models.ManyToManyField(blank=True, to='currency.Category', verbose_name='Categorías')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['registered'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galerías',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIF')),
                ('email', models.CharField(max_length=250, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('surname', models.CharField(blank=True, max_length=250, null=True, verbose_name='Apellidos')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('profile_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('profiles/'), verbose_name='Imagen de perfil')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('fav_entities', models.ManyToManyField(blank=True, to='currency.Entity', verbose_name='Favoritos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['registered'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Título')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=helpers.filesystem.RandomFileName('photos/'))),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='currency.gallery')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.gallery'),
        ),
        migrations.AddField(
            model_name='entity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
