# Generated by Django 3.2.7 on 2021-09-27 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('tax_processed', models.BooleanField(default=False, verbose_name='Impuestos procesados')),
                ('made_byadmin', models.BooleanField(default=False, verbose_name='Realizada por admin')),
                ('is_bonification', models.BooleanField(default=False, verbose_name='Bonificación')),
                ('is_euro_purchase', models.BooleanField(default=False, verbose_name='Compra de euros')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios adicionales')),
                ('rel_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.transaction')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WalletType',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('credit_limit', models.FloatField(default=0, verbose_name='Límite de crédito')),
                ('unlimited', models.BooleanField(default=False, verbose_name='Crédito ilimitado')),
            ],
            options={
                'verbose_name': 'Tipo de cuenta',
                'verbose_name_plural': 'Tipos de cuenta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=0, verbose_name='Saldo actual')),
                ('last_transaction', models.DateTimeField(blank=True, null=True, verbose_name='Última transacción')),
                ('pin_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código PIN (hasheado)')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallets.wallettype')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('amount', models.FloatField(default=0, verbose_name='Cantidad')),
                ('concept', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('made_byadmin', models.BooleanField(default=False, verbose_name='Realizada por admin')),
                ('is_bonification', models.BooleanField(default=False, verbose_name='Bonificación')),
                ('is_euro_purchase', models.BooleanField(default=False, verbose_name='Compra de euros')),
                ('current_balance', models.FloatField(default=0, verbose_name='Saldo')),
                ('related', models.TextField(blank=True, null=True, verbose_name='Concepto')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallets.transaction')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_logs', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='wallets.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='wallets.wallet'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('processed', models.DateTimeField(null=True, verbose_name='Timestamp procesado')),
                ('status', models.CharField(choices=[('accepted', 'Aceptado'), ('cancelled', 'Cancelado'), ('pending', 'Pendiente')], max_length=10)),
                ('total_amount', models.FloatField(default=0, verbose_name='Importe total')),
                ('currency_amount', models.FloatField(default=0, verbose_name='Cantidad en boniatos')),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['status'],
            },
        ),
    ]
